In [1]:
import numpy as np
import pandas as pd

# 1. Create 1D NumPy Array
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print("Week 1 Temperatures:")
print(temperatures_w1)

Week 1 Temperatures:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [2]:
# 2. Inspection and Properties
print("\nShape:", temperatures_w1.shape)
print("Data Type:", temperatures_w1.dtype)
print("Number of Elements:", temperatures_w1.size)


Shape: (7,)
Data Type: float64
Number of Elements: 7


In [3]:
# 3. Array Operations

# Celsius to Fahrenheit
fahrenheit = (temperatures_w1 * 9/5) + 32
print("\nTemperatures in Fahrenheit:")
print(fahrenheit)

print("\nMaximum Temperature:", np.max(temperatures_w1))
print("Minimum Temperature:", np.min(temperatures_w1))
print("Mean Temperature:", np.mean(temperatures_w1))



Temperatures in Fahrenheit:
[72.5  77.54 69.44 74.12 78.98 76.64 71.42]

Maximum Temperature: 26.1
Minimum Temperature: 20.8
Mean Temperature: 23.542857142857144


In [4]:
# 4. Array Slicing and Indexing

print("\nFirst Three Days:")
print(temperatures_w1[:3])

print("\nWeekend Temperatures:")
print(temperatures_w1[-2:])

print("\nMiddle Three Days:")
print(temperatures_w1[2:5])



First Three Days:
[22.5 25.3 20.8]

Weekend Temperatures:
[24.8 21.9]

Middle Three Days:
[20.8 23.4 26.1]


In [5]:
# 5. Create 2D Array

temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

print("\n2D Temperature Array:")
print(temperatures)



2D Temperature Array:
[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [6]:
# 6. Inspect and Slice 2D Array

print("\nShape:", temperatures.shape)
print("Data Type:", temperatures.dtype)
print("Total Elements:", temperatures.size)

print("\nWeek 1 Temperatures:")
print(temperatures[0])

print("\nWeek 2 Temperatures:")
print(temperatures[1])

print("\nWeekend Temperatures (Both Weeks):")
print(temperatures[:, -2:])



Shape: (2, 7)
Data Type: float64
Total Elements: 14

Week 1 Temperatures:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

Week 2 Temperatures:
[19.2 22.5 21.3 24.  23.5 22.8 20.1]

Weekend Temperatures (Both Weeks):
[[24.8 21.9]
 [22.8 20.1]]


In [7]:
# PANDAS SERIES

# 1. Creating Series

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print("\nMarks Series:")
print(marks)



Marks Series:
Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [8]:
# 2. Indexing and Slicing

print("\n1st Rank Student Mark:")
print(marks.iloc[0])

print("\nTop 3 Ranks:")
print(marks.loc[['Rank1', 'Rank2', 'Rank3']])

print("\n3rd Ranked Student Mark:")
print(marks.iloc[2])

print("\nMarks Greater Than 90:")
print(marks[marks > 90])


1st Rank Student Mark:
95

Top 3 Ranks:
Rank1    95
Rank2    92
Rank3    89
dtype: int64

3rd Ranked Student Mark:
89

Marks Greater Than 90:
Rank1    95
Rank2    92
dtype: int64


In [9]:
# 3. Manipulating Series

marks['Rank1'] = 100
print("\nAfter Updating Rank1 Mark:")
print(marks)

marks = marks.drop('Rank5')
print("After Removing Last Rank:")
print(marks)

cgpa = marks / 10
print("CGPA:")
print(cgpa)


After Updating Rank1 Mark:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64
After Removing Last Rank:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64
CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [10]:
# PANDAS DATAFRAME
# ==========================

# 1. Creating DataFrame

transactions = pd.DataFrame({
    'TransactionID': [101,102,103,104,105,106,107,108,109,110],
    'ProductCategory': [
        'Electronics','Clothing','Electronics','Furniture',
        'Clothing','Electronics','Furniture','Clothing',
        'Furniture','Electronics'
    ],
    'Region': [
        'North','South','North','East','West',
        'North','East','West','South','North'
    ],
    'Amount': [200,150,300,450,200,250,300,180,350,400]
})

In [11]:
# 2. Data Exploration

print("Transactions DataFrame:")
print(transactions)

print("Head:")
print(transactions.head())

print("Tail:")
print(transactions.tail())

print("Shape:")
print(transactions.shape)

print("Column Names:")
print(transactions.columns)

print("Data Types:")
print(transactions.dtypes)

print("ProductCategory and Amount:")
print(transactions[['ProductCategory', 'Amount']])

print("Last 3 Columns:")
print(transactions.iloc[:, -3:])

print("North Region and Amount > 200:")
print(
    transactions[
        (transactions['Region'] == 'North') &
        (transactions['Amount'] > 200)
    ]
)

print("Product Category Counts:")
print(transactions['ProductCategory'].value_counts())

print("Unique Regions:")
print(transactions['Region'].unique())

print("Mean Amount by Region:")
print(transactions.groupby('Region')['Amount'].mean())


Transactions DataFrame:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
Head:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
Tail:
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7   

In [12]:
# 3. Manipulating DataFrame

# Modify Amount for TransactionID 102
transactions.loc[
    transactions['TransactionID'] == 102,
    'Amount'
] = 165

# Add Discount Column
transactions['Discount'] = transactions['Amount'] * 0.10

print("\nAfter Adding Discount:")
print(transactions)


After Adding Discount:
   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0


In [13]:
# Remove TransactionID 109
transactions = transactions[
    transactions['TransactionID'] != 109
]

print("\nAfter Removing TransactionID 109:")
print(transactions)

# Delete Discount Column
transactions.drop(columns=['Discount'], inplace=True)

print("\nFinal DataFrame:")
print(transactions)


After Removing TransactionID 109:
   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

Final DataFrame:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furnitur